version: '3'

services:
  ncr_postgre:
    image: postgres:latest
    container_name: ncr_postgre
    ports:
       - "5432:5432"
    volumes:
      - ./dev_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: NCR


